name = "PosteriorPlots"
authors = ["hendersontrent <then6675@uni.sydney.edu.au> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.13"
julia = "1"

[targets]
test = ["Test"]
